import type { Content, Notification, AnonymizedConsumer } from '@/types';

export const MOCK_CONTENTS: Content[] = [
  {
    id: 'c001',
    creatorId: 'mock-creator',
    teaserUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    teaserDuration: 32,
    contentType: 'movie',
    status: 'approved',
    uploadedAt: '2026-03-12T18:04:00Z',
    approvedAt: '2026-03-13T10:00:00Z',
    exposureCount: 1284,
    interestCount: 87,
    title: '붉은 정원의 밤',
    synopsis: '한 가족이 정원에서 발견한 비밀, 그리고 시작되는 추적. 진실에 다가갈수록 균열이 깊어진다.',
    genres: ['drama', 'thriller'],
    directors: ['김지원'],
    releaseDate: '2026-03-15',
    ageRating: '15',
  },
  {
    id: 'c002',
    creatorId: 'mock-creator',
    teaserUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    teaserDuration: 28,
    contentType: 'drama',
    status: 'approved',
    uploadedAt: '2026-03-08T09:15:00Z',
    approvedAt: '2026-03-09T11:00:00Z',
    exposureCount: 892,
    interestCount: 54,
    title: '서울의 우체부',
    synopsis: '매일 같은 골목을 도는 우체부가 어느 날 배달하지 못한 편지 한 통을 발견한다.',
    genres: ['drama', 'romance'],
    directors: ['이수진'],
    releaseDate: '2026-04-01',
    ageRating: 'all',
  },
  {
    id: 'c003',
    creatorId: 'other-creator',
    teaserUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    teaserDuration: 22,
    contentType: 'drama',
    status: 'approved',
    uploadedAt: '2026-03-10T14:22:00Z',
    approvedAt: '2026-03-11T09:00:00Z',
    exposureCount: 431,
    interestCount: 19,
    title: '파랑의 기억',
    synopsis: '색을 잃은 도시에서 유일하게 파란색만 보이는 소녀의 이야기.',
    genres: ['fantasy', 'drama'],
    directors: ['박민준'],
    releaseDate: '2026-05-10',
    ageRating: '12',
  },
  {
    id: 'c004',
    creatorId: 'other-creator',
    teaserUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    teaserDuration: 18,
    contentType: 'book',
    status: 'approved',
    uploadedAt: '2026-03-11T16:48:00Z',
    approvedAt: '2026-03-12T08:00:00Z',
    exposureCount: 203,
    interestCount: 8,
    title: '이름 없는 계절',
    synopsis: '봄도 여름도 아닌 어딘가에서 머무는 두 사람.',
    genres: ['romance'],
    directors: ['최유나'],
    ageRating: 'all',
  },
];

// Pending contents for admin review
export const MOCK_PENDING: Content[] = [
  {
    id: 'p001',
    creatorId: 'creator_abc@email.com',
    teaserUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    teaserDuration: 42,
    contentType: 'movie',
    status: 'pending',
    uploadedAt: '2026-03-10T14:22:00Z',
    exposureCount: 0,
    interestCount: 0,
    title: '노을이 지는 방향',
    synopsis: '서로 다른 방향을 바라보던 두 사람이 마지막 노을 앞에 선다.',
    genres: ['romance', 'drama'],
    directors: ['정하늘'],
    releaseDate: '2026-06-01',
    ageRating: '12',
  },
  {
    id: 'p002',
    creatorId: 'creator_def@email.com',
    teaserUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    teaserDuration: 35,
    contentType: 'movie',
    status: 'pending',
    uploadedAt: '2026-03-11T09:15:00Z',
    exposureCount: 0,
    interestCount: 0,
    title: '철의 눈물',
    synopsis: '전쟁이 끝난 폐허에서 살아남은 병사가 마주한 진실.',
    genres: ['action', 'mystery'],
    directors: ['오태양'],
    ageRating: '15',
  },
  {
    id: 'p003',
    creatorId: 'creator_ghi@email.com',
    teaserUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4',
    teaserDuration: 18,
    contentType: 'book',
    status: 'pending',
    uploadedAt: '2026-03-12T19:50:00Z',
    exposureCount: 0,
    interestCount: 0,
    title: '3분의 침묵',
    synopsis: '매일 오후 3시, 3분 동안 아무것도 하지 않는 남자의 이야기.',
    genres: ['documentary'],
    directors: ['임소연'],
    ageRating: 'all',
  },
];

export const MOCK_CONSUMER_NOTIFICATIONS: Notification[] = [
  { id: 'n001', recipientUserId: 'mock-consumer', type: 'external_notice', relatedContentId: 'c001', isRead: false, createdAt: new Date(Date.now() - 2 * 60000).toISOString() },
  { id: 'n002', recipientUserId: 'mock-consumer', type: 'external_notice', relatedContentId: 'c002', isRead: true, createdAt: new Date(Date.now() - 3 * 3600000).toISOString() },
  { id: 'n003', recipientUserId: 'mock-consumer', type: 'external_notice', relatedContentId: 'c003', isRead: true, createdAt: new Date(Date.now() - 24 * 3600000).toISOString() },
];

export const MOCK_CREATOR_NOTIFICATIONS: Notification[] = [
  { id: 'cn001', recipientUserId: 'mock-creator', type: 'info_reveal', relatedContentId: 'c001', isRead: false, createdAt: new Date(Date.now() - 5 * 60000).toISOString() },
  { id: 'cn002', recipientUserId: 'mock-creator', type: 'info_reveal', relatedContentId: 'c001', isRead: false, createdAt: new Date(Date.now() - 30 * 60000).toISOString() },
  { id: 'cn003', recipientUserId: 'mock-creator', type: 'review_result', relatedContentId: 'c002', isRead: true, createdAt: new Date(Date.now() - 2 * 24 * 3600000).toISOString() },
];

export const MOCK_CONSUMERS: AnonymizedConsumer[] = [
  { anonymousId: 'anon-b7c3', userId: 1, ageGroup: '20대', gender: '여성', region: '서울', interestAt: new Date(Date.now() - 2 * 60000).toISOString(), noticeSent: false },
  { anonymousId: 'anon-a1f9', userId: 2, ageGroup: '30대', gender: '남성', region: '경기', interestAt: new Date(Date.now() - 3 * 3600000).toISOString(), noticeSent: true, noticeSentAt: new Date(Date.now() - 1 * 3600000).toISOString() },
  { anonymousId: 'anon-d4e2', userId: 3, ageGroup: '20대', gender: '여성', interestAt: new Date(Date.now() - 24 * 3600000).toISOString(), noticeSent: false },
  { anonymousId: 'anon-c8b1', userId: 4, ageGroup: '40대', gender: '남성', region: '부산', interestAt: new Date(Date.now() - 2 * 24 * 3600000).toISOString(), noticeSent: false },
];
